version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Assuming the name is Dockerfile
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Assuming the Dockerfile name is Docker.dev
    depends_on:
      - backend
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: my-postgres-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:latest  # Using the latest version of Keycloak
    environment:
      KEYCLOAK_USER: admin  # Default admin user
      KEYCLOAK_PASSWORD: 12345  # Default admin password
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: my-postgres-db
      DB_USER: root
      DB_PASSWORD: admin
    ports:
      - "5000:8080"
    depends_on:
      - postgres


# version: '3.8'
# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile  # Assuming the name is Dockerfile
#   frontend:
#     build:
#       context: ./shareclinextapp
#       dockerfile: Dockerfile  # Assuming the Dockerfile name is Docker.dev
#     depends_on:
#       - backend
#   nginx:
#     image: nginx:alpine
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx:/etc/nginx/conf.d
#     depends_on:
#       - frontend
#       - backend
